### ISSUE TITLE
First pass at a repository layout

### ISSUE THREAD

**Issue by ejhumphrey** [cosmir/open-mic#11]
Does not need to be permanent, but it'll be good to carve out space for how we see this garden growing.

**Comment by stefan-balke** [comment]
First shot on the `web_backend`:

--> web_backend
--->---> assets
--->--->---> css
--->--->---> js
--->--->---> img
--->---> templates
--->---> requirements/setup
--->--->---> requirements_dev.txt
--->--->---> requirements_production.txt

Pretty much standard so far.
Thoughts very welcome.

The question for me is what else should be in this repo? The web-backend should be task-agnostic so maybe another repo would be a better place to live.

**Comment by stefan-balke** [comment]
FWIW, this guy is a Flask guru and makes some good points in this tutorial about "Flask at scale" + he also has a book:
https://www.youtube.com/watch?v=tdIIJuPh3SI

**Comment by stefan-balke** [comment]
Based on that book, I would start with this tag:
https://github.com/miguelgrinberg/flasky/tree/7a

That got blueprints running and nicely separates the routes which otherwise will get messy pretty soon in the `app.py`. I give it a start and will also include the api @ejhumphrey started to implement.

**Comment by ejhumphrey** [comment]
pretty sure this is closed at this point (feel free to reopen if anyone feels differently)
