### ISSUE TITLE
Member introductions

### ISSUE THREAD

**Issue by vrangasayee** [cosmir/open-mic#14]
Can we have a quick round of introductions for who's who on this project. We can use this issue to introduce  or add a section to readme or wiki.

**Comment by ejhumphrey** [comment]
+100, this is a great idea! here works fine.

aside: will follow up with my own salutation when not on mobile.
On Aug 29, 2016 4:17 PM, "Vidya Rangasayee" <notifications@github.com>
wrote:

Can we have a quick round of introductions for who's who on this project.
We can use this issue to introduce or add a section to readme or wiki.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/omec/bedevere/issues/14>, or mute the thread

**Comment by ejhumphrey** [comment]
okay, I'll start!

Eric Humphrey here... I'm currently a machine learning researcher at Spotify, by way of a [PhD at NYU](https://github.com/ejhumphrey/dl4mir-dissertation/raw/master/EJHumphrey_DL4MIR_final.pdf) in 2015 and a [masters at UMiami](http://ejhumphrey.com/wp-content/uploads/2009/12/EJHumphrey_GMuEthesis.pdf) before that. I like neural networks, guitars, and [Siberian Huskies](http://imgur.com/gallery/1f9bF). 

I'm one of the authors on the ISMIR paper that kick-started this initiative, and will help serve as cheerleader, facilitator, and organizer on the project. In addition to making this actually happen, it is a particular goal of mine to achieve this in a democratic, consensus-driven fashion, and to do so with full transparency. Discussion topics like this are great (+1), and I hope others will spawn similar ones in the future.

**Comment by vrangasayee** [comment]
Vidya Rangasayee here. I work as an engineer with a startup in SF Bay Area. Prior to this I was with Amazon Music on their Android team and previously with Google in several capacities. I have a Masters in Scientific Computing from Stanford. MIR is a field that I am interested in. I designed and taught a course in MIR at San Jose State University in Fall 2015.  My plan is to enroll for a PhD at some point in the very near future. I saw this group as an opportunity to actively involve myself in the MIR community.

**Comment by julian-urbano** [comment]
Julián Urbano here. Along with @bmcfee and @ejhumphrey, I co-authored the paper that sparked this initiative and some others that tried to, but failed in similar attempts :laughing:

I'm currently a postdoc at [MTG Barcelona](http://mtg.upf.edu). About 99.9% of [my work](http://julian-urbano.info/publications/) is on (M)IR Evaluation, so I hope to be of help here. I've been wanting for something like this to happen for a number of years now, and I really hope we succeed and give birth to something great for everybody!

**Comment by ffont** [comment]
Frederic Font here. I'm doing post-doc at the [Music Technology Group](mtg.upf.edu). I'm deeply involved with the [AudioCommons](www.audiocommons.org) project and interested in Creative Commons audio. I also do [Freesound](www.freesound.org) development and maintenance at the MTG.

**Comment by alastair** [comment]
[Alastair Porter](http://www.dtic.upf.edu/~aporter/), [@alastairporter](https://twitter.com/alastairporter). I have a masters in Music Technology from McGill. I work as a researcher, programmer, sysadmin, code reviewer, ideas wall at [Music Technology Group](http://mtg.upf.edu).
I'm working with @ffont on AudioCommons, but am also a significant contributor to [MusicBrainz](https://musicbrainz.org) and am the lead for the AcousticBrainz project (where we're also thinking about a lot of this annotation stuff)

**Comment by bmcfee** [comment]
[Brian McFee](http://bmcfee.github.io/), and as mentioned above by @ejhumphrey and @julian-urbano, I'm the other coauthor of the paper behind this project.  I'm a researcher at NYU's [Center for Data Science](http://cds.nyu.edu/) and [Music and Audio Research Lab](http://steinhardt.nyu.edu/marl/), and generally hack on a bunch of open source projects in support of MIR research.

**Comment by markostam** [comment]
Hey guys, Marko Stamenovic here. I recently finished a masters in Audio DSP from the University of Rochester where I am currently a research consultant with the [Institute for Data Science](institute for data science columbia) and also a collaborator with the [Audio Information Research Lab](http://www.ece.rochester.edu/projects/air/index.html). Also, I am about to join the [Recurse Center](https://www.recurse.com) for a 3-month batch, where I plan to devote a good amount of time to this project. I'm excited to work on a project that I think has potential to make a great positive impact and get more involved with the MIR community as a whole.

**Comment by franrodalg** [comment]
Hi folks! Fran Rodríguez here. I'm a PhD student @ [C4DM](http://c4dm.eecs.qmul.ac.uk/) in London, under the supervision of the Horse Master [Bob L. Sturm](https://highnoongmt.wordpress.com/2015/07/02/i-am-known-as-that-guy-but-really-i-am-that-other-guy/). Previously I got a Master's Degree @ MTG in Barcelona.
My current research is entirely focused on attempting to improve MIR evaluation practices. Getting involved in this community-based effort is, then, almost a must for me. 

I honestly believe that there is still much work to be done in [fixing the foundations of MIR evaluation](https://wp.nyu.edu/ismir2016/wp-content/uploads/sites/2294/2016/07/128_Paper.pdf) so that we can extract valid, reliable and relevant conclusions from our studies. Even though I am aware that the main goal of this challenge is not to avoid [horses](http://c4dm.eecs.qmul.ac.uk/horse2016/), I think it might provide an amazing chance to discuss about these issues, and many more, that concern me deeply. In addition to that, I think that participating here will allow me to have a much more "realistic" perspective about the needs of system developers and the practical limitations to evaluation. It's time to stop criticising from the outside and start suggesting solutions!

I plan to do some analyses about the stuff we discuss around here in my shiny new [blog](https://rhapsodyinmu.wordpress.com/), which is currently under construction. Any comments and/or criticisms are highly welcome!

**Comment by douglaseck** [comment]
Hi all. I'm Doug Eck. I'm a research scientist
<http://research.google.com/pubs/author39086.html>at Google. I'm leading
Magenta <http://magenta.tensorflow.org> a Google Brain
<https://research.google.com/teams/brain/> open-source project devoted to
music and art generation using deep learning and reinforcement learning.
I've been working on MIR for a long time. Before coming to Google I was an
associate professor in computer science at the University of Montreal.

I'm hoping that OMEC can grow in such a way that it's possible for
companies like Google, Facebook, Spotify and Pandora to take part in the
effort.

**Comment by dmcennis** [comment]
Hello,
I'm Daniel McEnnis. I started in MIR in 2000, joined the ISMIR community through McGill in 2005, and switched to Silicon Valley in 2011. I've been involved in countless evaluation projects, starting with OMEN and the 07 ISMIR projects, continuing nearly continuously to this date. My most recent project is with Research at Scale which I founded in 2014. I am currently developing artificial sentient life work for that company and renovating my new home. It's been a long absence, but I'm hoping to reconnect with my original academic peer group and bring back to the table my experience in automated evaluation technologies.

**Comment by santoshchapaneri** [comment]
Hi all, I am Santosh Chapaneri from India.
I did my MS (ECE) from University of Arizona and worked with iGate (India)
as DSP Engineer and at Microsoft, Seattle (USA) as a Software Developer on
the Digital Memories Experience Team. Currently, I am back to academics as
a faculty at University of Mumbai (India) and have recently started PhD in
the exciting area of MIR. Looking forward to learn a lot from this
community!
​​
Very much interested to see how the ideas presented by Bob Sturm et al. in
the paper Formalizing the problem of Music Description
<https://hal.inria.fr/hal-01016189/document> and other notions of
evaluation (as also mentioned by Francisco) takes shape at a large scale.

**Comment by dbogdanov** [comment]
Hi all, Dmitry Bogdanov here. I am a post-doc at the [Music Technology Group](http://mtg.upf.edu/). I am the main developer for [Essentia](http://essentia.upf.edu/) open-source audio analysis library and together with @alastair I am deeply involved with the [AcousticBrainz](http://acousticbrainz.org) project in which Essentia is used. I am also a member of the AudioCommons project. I am mostly interested in development and QA of audio features  and evaluation of machine learning approaches for semantic annotation (currently, mostly classifiers).

**Comment by justinsalamon** [comment]
Hola everyone, [Justin Salamon](www.justinsalamon.com) here (currently breaking my no-work-on-vacation-rule). Postdoc at NYU's [Music and Audio Research Lab](http://steinhardt.nyu.edu/marl/) and [Center for Urban Science and Progress](http://cusp.nyu.edu) (also part of the [MTG](www.mtg.upf.edu) family by way of PhD), working at the intersection of ML and audio across different-yet-related domains (music, environmental sound & bioacoustics). 

Having experienced the problems of eval in MIR [first hand](http://www.justinsalamon.com/uploads/4/3/9/4/4394963/salamonurbanomelodymetaeval_ismir12.pdf)  with @julian-urbano (but then I guess everyone here has), keen to help make things better :)

**Comment by jtcramer** [comment]
Hi folks, I'm Jason Cramer. I'm a research engineer at Gracenote, coming from UC Berkeley where I got my B.S. in EECS. I'm looking forward to getting more involved in the MIR community, learning more, and building useful things!

**Comment by urinieto** [comment]
Hi there, titans. I'm [Uri Nieto](http://urinieto.com/), an MIR scientist at Pandora. I pursued my PhD at MARL, NYU, with other great people in this project. In my [dissertation](http://marl.smusic.nyu.edu/nieto/publications/Nieto-Dissertation.pdf) I tried to expose some of the current limitations in the evaluation of music structural segmentation.

Currently, I do research on machine learning applied to music in order to improve Pandora's recommender system and, more generally, to save the world. Deep learning, python, vim, beer, yoga and screaming are things that I highly enjoy.

**Comment by stefan-balke** [comment]
Hi, I'm [Stefan Balke](https://www.audiolabs-erlangen.de/fau/assistant/balke), currently pursuing a PhD at the [AudioLabs](https://www.audiolabs-erlangen.de). In the past, I highly benefitted from tools like `librosa` or `mir_eval` and think it's a good opportunity to pay something back to this awesome community.

**Comment by sergiooramas** [comment]
Hi, here Sergio Oramas, last year phd student at the Music Technology Group
in Barcelona. My phd is about nlp applied to mir, so i know a bit about nlp
challenges and evaluation frameworks. Lately I've been also very much into
deep learning after an internship in Pandora.

I think the mir community needs something like this and there are many
things we can learn from other research communities.

Sergio

**Comment by constd** [comment]
Hi, I'm Constantinos Dimitriou, like @jtcramer, I'm a Research Engineer at Gracenote, although I arrived here after getting my MSc from MTG. I've been interested in the understanding of algorithms and their (proper) evalutation on MIR for a while now. I agree with @sergiooramas that the MIR community needs something like this and I'm looking forward to getting more involved, learning and contributing.

**Comment by karoldvl** [comment]
Hi everyone! A new latecomer here, but fortunately, thanks to @justinsalamon, I got to know about this project in the end.

I'm currently pursuing a PhD in convolutional neural networks for sound classification at the [Warsaw University of Technology](https://www.pw.edu.pl/engpw), mostly concentrating on environmental sounds/bioacoustics, with some small parts being related to musical instrument recognition. Apart from that, I have some background (Masters) in Finance, and in my free time I (used to) do some hobbyist musical composition/production, by way of which I've become an aficionado of various software synths and sample libraries.

**Comment by ejhumphrey** [comment]
great enthusiasm, closing this first round of intros
