### ISSUE TITLE
Annotation storage: SQL or NoSQL

### ISSUE THREAD

**Issue by stefan-balke** [cosmir/open-mic#23]
Hi,

I'd like to trigger the discussion about "how we want to store the annotations"
to decide if an SQL or NoSQL backend should be used.

I only have experience with SQL architectures so far. Until now, all my annotations could be easily modelled with a relational paradigm. Any thoughts on this? Experiences?

**Comment by ejhumphrey** [comment]
per the proposal of sorts I hashed out [here](https://docs.google.com/document/d/1_Ta7I8liVUq29GVbmvHYhv4iXc_ybw72_POA5GPUdNc/edit), I'm advocating the use of Google Compute Platform (GCP) as our cloud tech solution. This would mean that we:
- run the backend content management server in App Engine
- store JSON, e.g. annotations, user data, etc, in DataStore
- store binary, e.g. audio, data in Google Cloud Storage

The rationale being:
- For *simple* Flask apps, [App Engine](https://cloud.google.com/appengine/) is as good as it gets. It provides autoscaling / load balancing, so that we don't have to worry about growth whatsoever, and integrates nicely with other GCP tech.
- [DataStore](https://cloud.google.com/datastore/), which is NoSQL, provides ACID transactions, fantastic search / indexing capabilities, and is a breeze.
- not much to say about [Cloud Storage](https://cloud.google.com/storage/), it does exactly what it should really well.

I've been using GCP for a few months now, and much prefer it to AWS's offerings, or attempting to manage our own instances / databases, e.g. Mongo.

**Comment by vrangasayee** [comment]
I would suggest noSQL as well due to the following
1. Easy JSON format to help quick development
2. Flexible to accommodate different annotation data. This can be achieved
in SQL but needs much more design effort
3. Fast searches including free text
4. Can support ACID but not sure how big of a requirement this would be for
the annotations.

Thanks
Vidya

**Comment by stefan-balke** [comment]
- store JSON, e.g. annotations, user data, etc, in DataStore

And `jams` is already there. Starting to get where this is going...

Yeah, then NoSQL.

But, also for things like user accounts?

**Comment by ejhumphrey** [comment]
Ya, DataStore is great for mutable records shared across applications / instances (hence, ACID transactions) ... so we can store a user's submitted annotations, as well as return them if they chose to edit a previous response. Same goes for caching our data model / state of a given user, such as the last thing they saw, tracking progress, etc.

**Comment by ejhumphrey** [comment]
BTW, for anyone curious, I highly recommend signing up for a free trial of GCP and playing with the tools. It's remarkably painless.

docs: https://googlecloudplatform.github.io/google-cloud-python/stable/
on gh: https://github.com/GoogleCloudPlatform/google-cloud-python
